api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "points-redemption"
type = "function"
uid = "a9c5d37b-f73c-e9eb-4b20-dc7ecdc983ee629017bc"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
