# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3acb5c90ed6b779288c26dee2a0bf291"
name = "habit"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://example.com/webhooks/customers/redact"
  customer_data_request_url = "https://example.com/webhooks/customers/data_request"
  shop_deletion_url = "https://example.com/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = [ "refunds/create" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,read_discounts,write_discounts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/proxy"
subpath = "habit"
prefix = "apps"
